// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDApWzTGExJDPs66HYhEtiDUEFCSJ2euzA',
    appId: '1:304419903921:web:e1695060c75fcf58318590',
    messagingSenderId: '304419903921',
    projectId: 'cookeasy-bcb38',
    authDomain: 'cookeasy-bcb38.firebaseapp.com',
    storageBucket: 'cookeasy-bcb38.appspot.com',
    measurementId: 'G-CXFPR3NNBJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyl-8k8x0VWPIIQ5Y-rngWRSChQpJdyxk',
    appId: '1:304419903921:android:2bd4479dcdfed75f318590',
    messagingSenderId: '304419903921',
    projectId: 'cookeasy-bcb38',
    storageBucket: 'cookeasy-bcb38.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBy9Cmr7gvXAdClmkepgLHgc8JL3rdLl34',
    appId: '1:304419903921:ios:55e99582902f2960318590',
    messagingSenderId: '304419903921',
    projectId: 'cookeasy-bcb38',
    storageBucket: 'cookeasy-bcb38.appspot.com',
    iosClientId: '304419903921-45s61nov4a8pd64spmj6fujf3biin3v8.apps.googleusercontent.com',
    iosBundleId: 'com.example.chefio1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBy9Cmr7gvXAdClmkepgLHgc8JL3rdLl34',
    appId: '1:304419903921:ios:55e99582902f2960318590',
    messagingSenderId: '304419903921',
    projectId: 'cookeasy-bcb38',
    storageBucket: 'cookeasy-bcb38.appspot.com',
    iosClientId: '304419903921-45s61nov4a8pd64spmj6fujf3biin3v8.apps.googleusercontent.com',
    iosBundleId: 'com.example.chefio1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDApWzTGExJDPs66HYhEtiDUEFCSJ2euzA',
    appId: '1:304419903921:web:565dded8d6c65e3e318590',
    messagingSenderId: '304419903921',
    projectId: 'cookeasy-bcb38',
    authDomain: 'cookeasy-bcb38.firebaseapp.com',
    storageBucket: 'cookeasy-bcb38.appspot.com',
    measurementId: 'G-BXQNKP469L',
  );
}
